### ISSUE TITLE
GitHub Action help request

### ISSUE THREAD

**Issue by CraigWatt** [joncrain/munkipkg-action#3]
Hi @joncrain, 

I'd like to use this GitHub action (munkipkg-action) for my project [vfo](https://github.com/CraigWatt/vfo).

Here is my [current vfo workflow](https://github.com/CraigWatt/vfo/blob/6f0ee3c20eeda8898ac14eb71144f3c99c767fa8/.github/workflows/on-tags-push.yml#L62).  It uses munkipkg but to do this I downloaded munkipkg and included it as part of the vfo repo itself.

**Do you think I could use your Action instead to achieve the same results?**  I'm keen to get munkipkg OUT of my repo to avoid confusion for anyone looking at my project.

**Comment by joncrain** [comment]
You are definitely welcome to use. I don't see why you couldn't use it. Here is an example: https://github.com/joncrain/test-munki-pkg/blob/main/.github/workflows/munkipkg.yml

**Comment by CraigWatt** [comment]
Hey Jon, 

Just letting you know that this action is now working for my project!

(See on-tags-push.yml workflow line 73)

https://github.com/CraigWatt/vfo

Thanks again,
Craig
